exports.SUCCESSFULLY = 'SUCCESSFULLY';

exports.ADMIN_ALREADY_REGISTERED= 'ADMIN_ALREADY_REGISTERED';

exports.SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG';

exports.INVALID_PASSWORD = 'INVALID_PASSWORD';

exports.SIGN_OUT_SUCCESSFULLY = 'SIGN_OUT_SUCCESSFULLY';

exports.AUTHORIZATION_REQUIRED ='AUTHORIZATION_REQUIRED';

exports.USER_ACCESS_DENIED = 'USER_ACCESS_DENIED';


exports.ADMIN_ACCESS_DENIED = 'ADMIN_ACCESS_DENIED';
